appnope==0.1.2
argon2-cffi==21.1.0
asgiref==3.4.1
attrs==21.2.0
backcall==0.2.0
bcrypt==3.2.0
beautifulsoup4==4.10.0
bigquery==0.0.16
bleach==4.1.0
boto3==1.18.62
botocore==1.21.62
Brotli==1.0.9
bs4==0.0.1
cachetools==4.2.4
certifi==2021.5.30
cffi==1.14.6
charset-normalizer==2.0.4
click==8.0.1
cryptography==35.0.0
cycler==0.10.0
dacktool==0.0.7
dash==2.0.0
dash-bootstrap-components==0.13.1
dash-colorscales==0.0.4
dash-core-components==2.0.0
dash-daq==0.5.0
dash-html-components==2.0.0
dash-table==5.0.0
datatable==1.0.0
dbstream==0.1.6
debugpy==1.4.3
decorator==5.1.0
defusedxml==0.7.1
Django==3.2.8
dtale==1.58.3
entrypoints==0.3
et-xmlfile==1.1.0
Flask==2.0.1
Flask-Compress==1.10.1
flask-ngrok==0.0.25
future==0.18.2
geographiclib==1.52
geopy==2.2.0
google-api-core==2.1.1
google-api-python-client==1.7.11
google-auth==2.3.0
google-auth-httplib2==0.0.3
google-auth-oauthlib==0.4.6
google-cloud-bigquery==2.28.1
google-cloud-bigquery-storage==2.9.1
google-cloud-core==2.1.0
google-cloud-storage==1.42.3
google-crc32c==1.3.0
google-resumable-media==2.0.3
googleapis-common-protos==1.53.0
googleauthentication==0.0.15
grpcio==1.41.0
httplib2==0.20.1
idna==3.2
ipykernel==6.4.1
ipython==7.27.0
ipython-genutils==0.2.0
ipywidgets==7.6.5
itsdangerous==2.0.1
jedi==0.18.0
Jinja2==3.0.1
jmespath==0.10.0
joblib==1.0.1
jsonschema==3.2.0
jupyter==1.0.0
jupyter-client==7.0.3
jupyter-console==6.4.0
jupyter-core==4.8.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.2
kaleido==0.2.1
kiwisolver==1.3.2
libcst==0.3.21
lxml==4.6.3
lz4==3.1.3
MarkupSafe==2.0.1
matplotlib==3.4.3
matplotlib-inline==0.1.3
missingno==0.4.2
mistune==0.8.4
mpmath==1.2.1
multitasking==0.0.9
mypy-extensions==0.4.3
nbclient==0.5.4
nbconvert==6.1.0
nbformat==5.1.3
nest-asyncio==1.5.1
networkx==2.6.3
notebook==6.4.4
numpy==1.21.2
oauthlib==3.1.1
openpyxl==3.0.9
packaging==21.0
pandas==1.3.3
pandocfilters==1.5.0
paramiko==2.8.0
parso==0.8.2
patsy==0.5.2
pexpect==4.8.0
pgeocode==0.3.0
pickleshare==0.7.5
Pillow==8.3.2
plotly==5.3.1
polars==0.9.8
ppscore==1.2.0
prometheus-client==0.11.0
prompt-toolkit==3.0.20
proto-plus==1.19.5
protobuf==3.18.1
ptyprocess==0.7.0
pyarrow==5.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
Pygments==2.10.0
PyNaCl==1.4.0
pyparsing==2.4.7
pyrsistent==0.18.0
python-dateutil==2.8.2
pytz==2021.1
PyYAML==6.0
pyzmq==22.3.0
qtconsole==5.1.1
QtPy==1.11.1
requests==2.26.0
requests-mock==1.9.3
requests-oauthlib==1.3.0
rsa==4.7.2
s3transfer==0.5.0
scikit-learn==0.24.2
scipy==1.7.1
seaborn==0.11.2
Send2Trash==1.8.0
six==1.16.0
sklearn==0.0
sodapy==2.1.0
soupsieve==2.2.1
sqlparse==0.4.2
squarify==0.4.3
sshtunnel==0.1.5
statsmodels==0.13.0
strsimpy==0.2.1
sympy==1.8
tenacity==8.0.1
terminado==0.12.1
testpath==0.5.0
threadpoolctl==2.2.0
torch==1.9.0
torchvision==0.10.0
tornado==6.1
tqdm==4.62.3
traitlets==5.1.0
typing-extensions==3.10.0.2
typing-inspect==0.7.1
uritemplate==3.0.1
urllib3==1.26.6
wcwidth==0.2.5
webencodings==0.5.1
Werkzeug==2.0.1
widgetsnbextension==3.5.1
xarray==0.19.0
xlrd==2.0.1
yahoofinancials==1.6
yfinance==0.1.63
